services:
  sentiment-service:
    image: manaswini6i/sentiment-service:latest
    container_name: sentiment-service
    ports:
      - "8000:8000"
    restart: unless-stopped

  languagetool:
    image: erikvl87/languagetool:latest
    container_name: languagetool
    restart: unless-stopped
    ports:
      - "8010:8010"

  grammar-service:
    image: manaswini6i/grammar-service:latest
    container_name: grammar-service
    environment:
      - LANGUAGETOOL_URL=http://languagetool:8010
    ports:
      - "8001:8001"
    depends_on:
      - languagetool
    restart: unless-stopped



  frontend:
    image: manaswini6i/nlp-toolkit-frontend:latest
    container_name: frontend
    ports:
      - "8080:80"
    restart: unless-stopped
