services:
  sentiment-service:
    build: ./cloudsentimentService
    container_name: sentiment-service
    ports:
      - "8000:8000"
    restart: unless-stopped

  languagetool:
    image: erikvl87/languagetool:latest
    container_name: languagetool
    restart: unless-stopped
    ports:
      - "8010:8010"

  grammar-service:
    build: ./grammerService
    container_name: grammar-service
    environment:
      - LANGUAGETOOL_URL=http://languagetool:8010
    ports:
      - "8001:8001"
    depends_on:
      - languagetool
    restart: unless-stopped


  frontend:
    image: nginx:alpine
    container_name: frontend
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
    restart: unless-stopped